version: '3.8'

services:
  interpelbot:
    image: harbor-dev.venceremos.eu/bots/interpelbot:latest
    container_name: interpelbot
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 100
        window: 120s
    environment:
      - TZ=Europe/Warsaw
      # Konfiguracja InterpelBot - edytuj plik config.json
    volumes:
      # Mount data directory for persistence
      - /opt/interpelbot/data:/app/data
      # Mount logs directory
      - /opt/interpelbot/logs:/var/log
    healthcheck:
      test: ["CMD", "pgrep", "crond"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 